#!/bin/bash

echo "🔧 强制设置Gradle用户目录..."

# 1. 设置环境变量
export GRADLE_USER_HOME="/Users/chenlei/.gradle"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"

echo "📂 强制设置GRADLE_USER_HOME: $GRADLE_USER_HOME"
echo "☕ 设置JAVA_HOME: $JAVA_HOME"

# 2. 在gradle.properties中强制设置
echo "📝 在gradle.properties中强制设置Gradle用户目录..."
cat > gradle.properties << 'EOF'
# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# 强制设置Gradle用户目录
org.gradle.user.home=/Users/chenlei/.gradle

# 网络配置
systemProp.http.proxyHost=
systemProp.http.proxyPort=
systemProp.https.proxyHost=
systemProp.https.proxyPort=

# 超时配置
systemProp.http.connectionTimeout=60000
systemProp.http.socketTimeout=60000

# AndroidX package structure
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Enable namespacing
android.nonTransitiveRClass=true

# Gradle配置
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
EOF

# 3. 确保Gradle用户目录存在并有正确权限
echo "📁 确保Gradle用户目录存在..."
mkdir -p "$GRADLE_USER_HOME"
mkdir -p "$GRADLE_USER_HOME/wrapper/dists"
chmod -R 755 "$GRADLE_USER_HOME"

# 4. 清理可能的问题文件
echo "🧹 清理可能的问题文件..."
rm -rf "$GRADLE_USER_HOME/wrapper/dists/gradle-8.2-bin"

# 5. 创建local.properties文件强制设置
echo "📝 创建local.properties文件..."
cat > local.properties << EOF
# This file was automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
sdk.dir=/Users/chenlei/Library/Android/sdk
EOF

# 6. 停止所有Gradle守护进程
echo "🛑 停止所有Gradle守护进程..."
./gradlew --stop 2>/dev/null || true

# 7. 设置环境变量并尝试构建
echo "🚀 尝试构建项目..."
export GRADLE_USER_HOME="/Users/chenlei/.gradle"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
export PATH="$JAVA_HOME/bin:$PATH"

echo "环境变量验证:"
echo "GRADLE_USER_HOME=$GRADLE_USER_HOME"
echo "JAVA_HOME=$JAVA_HOME"

# 尝试构建
./gradlew clean --info





